services:
  dealii_workbench:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: parabolische_inverse_probleme
    volumes:
      - ./:/home/dealii/workdir
    working_dir: /home/dealii/workdir
    user: "dealii:dealii"
    command: tail -f /dev/null


