version: '3'
services:
  dealii_workbench:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: parabolische_inverse_probleme
    volumes:
      - ./:/workdir
    user: "root:root"
    command: tail -f /dev/null


